### ISSUE TITLE
cannot download from gopkgs.com/dl.v1

### ISSUE THREAD

**Issue by wangkirin** [rainycape/dl#3]
when I execute `go get gopkgs.com/dl.v1` , returns  `package gopkgs.com/dl.v1: unrecognized import path "gopkgs.com/dl.v1" `
and when I visit  `gopkgs.com` on browser, the page shows `502 Bad Gateway`,could you fix that ?thanks

**Comment by mwmahlberg** [comment]
Just found out that the whole ["gopkgs.com" domain is no longer available](http://centralops.net/co/DomainDossier.aspx?addr=gopkgs.com&dom_dns=true). You need to clone the report into your `$GOPATH/src` directory and install from there.

I'd suggest to the author to move to [gopkg.in](http://labix.org/gopkg.in) instead.

**Comment by mwmahlberg** [comment]
Actually you can already use gopkg.in

    go get "gopkg.in/rainycape/dl.v0"

**Comment by wangkirin** [comment]
@mwmahlberg  Problem Sloved, thx!

**Comment by rainycape** [comment]
My apologies for being late. I thought we had moved all our packages off gopkgs.com, but I missed this one and a couple more. It should be fixed now, you should be able to import it directly from github.
